config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => {:registrations => "registrations"}
  #devise_for :users,  :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => {:registrations => "user_registrations"}
  resources :users
	resources :users, only: [:products, :index, :show, :create, :destroy]
  resources :posts #Added in 5.5
  resources :orders, only: [:index, :show, :create, :destroy]

  resources :products do
    resources :comments
  end

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  get 'static_pages/landing_page'

  get 'orders/index'

  get 'orders/show'

  get 'users/form'

  get 'users/show'

  get 'users/index'

  get 'users/edit'

  get 'users/new'

  post 'payments/create'
  get 'payments/create'

  #get '/products', to: 'products#index' #Example: Get request for non-static page (cf. ex. 5.1)

  #root 'static_pages#index' #The first root entry defines which page will be shownwhen the application receives a request without a path (i.e. hocalhost:3000)
  
  root 'static_pages#landing_page' #This root will be ignored because the root to 'static_pages#index is first in line. // Sets the root of the rails app to the controller static_pages and the landing page. The controller for the static page needs to be referenced in the routes.rb file like this. Otherwise, the user cannot access the page.
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post 'static_pages/thank_you'

  mount ActionCable.server => '/cable'
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@product = Product.find(params[:product_id])
		@comment = @product.comments.new(comment_params)
		@comment.user = current_user
		#@comment.save
		#redirect_to product_path(@product)
		respond_to do |format|
			if @comment.save
				ActionCable.server.broadcast 'product_channel', comment: @comment, average_rating: @comment.product.average_rating
				format.html { redirect_to @product, notice: 'Review was created successfully.' }
				format.json { render :show, status: :created, location: @product }
				format.js  
			else
				format.html { redirect_to @product, alert: 'Review was not saved successfully.' }
				format.json { render json: @comment.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@comment = Comment.find(params[:id])
		product = @comment.product
		@comment.destroy
		redirect_to product
	end

	private

	def comment_params
		params.require(:comment).permit(:user_id, :body, :rating)
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json

  def index
    if params[:q]
      search_term = params[:q]
      @products = Product.search(search_term)
      logger.debug "Product: #{@products}"
    else
      @products = Product.all
    end
    @products = Product.order("name").page(params[:page]).per_page(5)
    logger.debug "Product: #{@products}"
  end

  # GET /products/1
  # GET /products/1.json
  def show
   # @comments = @product.comments.order("created_at DESC")
    @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
    logger.debug "Comments: #{@comments}"
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_url, notice: 'Product was successfully created.' } #Cf. redirect entry in destroy method    
        #format.html { redirect_to @product, notice: 'Product was successfully created.' } #This is the original entry which redirects to product details without image
        #format.html { redirect_back, notice: 'Product was successfully created.' } #Causes 500 internal server error.
        #format.html { redirect_to "/products/index.html.erb", notice: 'Product was successfully created.' } Tried to redirect to product page but failed.
        
        format.json { render :show, status: :created, location: @product }

      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_url, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/comments/_comment.html.erb
<div class="row">
  <hr>
  <p>
    <%= comment.user.first_name %>  <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
    <% if signed_in? && current_user.admin? %>
      <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(comment.product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </p>
  <div class="rated" data-score="<%= comment.rating %>"></div>
  <p><%= comment.body %></p>
  <
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>RailsApp</title>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
		<%= csrf_meta_tags %>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
		<meta name="viewport" content="width=device-width, initial-scale=1">
			<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
			<![endif]-->
		 <!-- FACEBOOK -->
		<div id="fb-root"></div>
		<script>(function(d, s, id) {
			var js, fjs = d.getElementsByTagName(s)[0];
			if (d.getElementById(id)) return;
			js = d.createElement(s); js.id = id;
			js.src = "//connect.facebook.net/de_DE/sdk.js#xfbml=1&version=v2.9";
			fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));</script>

			 <!-- TWITTER -->
		<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
		<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
	</head>

	<body data-spy="scroll" data-target=".navbar">
		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container-fluid" id="container-nav">
				<nav class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar.collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<nav class="projectName navbar-brand">
						<a href="/static_pages/landing_page">THE MOTORCYCLE SHOP</a>
					</nav><!--END PROJECT NAME-->
				</nav><!--END NAVBAR HEADER-->
				<nav class="navbar-collapse collapse">
					<ul class="nav navbar-nav navbar-right" id="nav">
						<li><a href="/static_pages/index"><span class="glyphicon glyphicon-home"></span></a></li>
						<li><a href="/static_pages/about">About</a></li>
						<li><a href="/products/">Motorbikes</a></li>
						<li><a href="/static_pages/contact">Contact</a></li>
						<li>
							<div class="form-group navbar-form navbar-right" role="search">
								<%= form_with(url: products_path, method: 'get', local: true) do |form| %>
									<%= form.label :q, 'Search for:', class: 'sr-only' %>
									<%= form.text_field :q, id: 'q', value: params[:q], placeholder: 'search for products', class: 'form-control' %>
									<%= form.submit 'Search', class: 'btn' %>
								<% end %>
							</div><!-- END form-group -->
						</li>
						<li>
							<% if user_signed_in? %>
								<%= link_to('Logout', destroy_user_session_path, method: :delete) %>
							<% else %>
								<%= link_to('Login', new_user_session_path) %>
							<% end %>
						</li>
					</ul><!-- end nav-list -->
				</nav><!-- END navbar-collapse -->
			</div><!--end nav container -->
		</nav><!--end navbar -->
		<%if notice %>
		<p id="notice" class="alert alert-info"><%= notice %></p>
		<% end %>
		<% if alert %>
		<p id="alert" class="alert alert-info"><%= alert %></p>
		<% end %>


		<%= yield %>

			<footer class ="site-footer">
				<div class="container" id="container-footer">
							 <!-- TWITTER -->
				<a href="https://twitter.com/ulfschuster" class="twitter-follow-button" id="foot" data-show-screen-name="false" data-show-count="false">Follow @ulfschuster</a>

								<!-- FACEBOOK -->
				<div class="fb-like" id="foot" data-href="https://schuster-ulf-36311.bitballoon.com" data-layout="standard" data-action="like" data-size="small" data-show-faces="false" data-share="true">
				</div>
				<p>&copy MOTORCYCLES, INC. 2017</p>
				</div><!-- END container footer -->
			</footer>
	</body>
</html>

app/views/products/_product.html.erb
<% cache product do %>
  <div class="col-products col-xs-12 col-sm-6 col-md-4 col-lg-3">
    <%# if( Rails.env.production(Rails.application.assets_manifest.find_sources(product.image_url) != nil %>
    <%# if(Rails.application.assets.find_asset(product.image_url) != nil) %>
    <picture><%= image_tag(product.image_url, width: "450", height: "400", class: "img-responsive") %></picture>
    <%# end %>
    <p><%= product.name %></p>
    <p><%= product.description %></p>
    <p>Colour: <%= product.colour %></p>
    <p>Price: €<%= product.price %></p>
    <%= link_to 'Show', product %>
    <%= link_to 'Edit', edit_product_path(product) %>
    <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
<% end %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<div class="container-fluid">
  <div class="row">
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
		<% cache (cache_key_for_products) do %> 
		    <% @products.each do |product| %>
		      	<%= render partial: "product", locals: {product: product} %>
		    <% end %>
		 <% end %>
	</div>
  </div>
</div>
<hr>
<div class="text-center"><%= will_paginate @products %></div>
<% if user_signed_in? && current_user.admin? %>
	<%= link_to 'Add New Product', new_product_path %>
<% end %>
<hr>

app/views/products/show.html.erb
<div class="container-fluid">
<p id="notice"><%= notice %></p>
<picture><%= image_tag(@product.image_url,  width: "450", class: "img-responsive img-zoom", data_zoom_image: "@product.image_url") %></picture><br>
</div><!-- end container-fluid -->
<% cache @product do %>

<p>
	<strong>Name:</strong>
	<%= @product.name %>
</p>

<p>
	<strong>Description:</strong>
	<%= @product.description %>
</p>
<% end %>
<p>
	<strong>Image url:</strong>
	<%= @product.image_url %>
</p>

<p>
	<strong>Colour:</strong>
	<%= @product.colour %>
</p>

<p>
	<strong>Price: €</strong>
	<%= @product.price %>
</p><br>

<p>
	<strong>Average Rating:</strong>
	<div class="rated" data-score="<%= @product.average_rating %>"></div>
</p><br>

<div>
	<%= form_tag "/payments/create" do %>
        <%= hidden_field_tag(:product_id, @product.id) %>
        <%= render partial: 'shared/stripe_checkout_button' %>
     <% end %>   
</div>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>
<div class= "comments">
    <h2>Comments</h2>
    <p><%= @product.highest_rating_comment.try(:rating) %><p>
        <%= render 'new_comment' %>
        <div class="alert alert-info" style="display:none" role="alert">A new comment was posted!</div>
        <%= render 'comments' %>
</div>
<div class="text-center col-xs-12">
    <%= will_paginate @comments %>
</div>      

app/views/static_pages/contact.html.erb
<% cache do %>
  <% sleep 2 %>
<h1>Contact Us</h1>
<% end %>

<%= flash[:notice] %>

<%= form_with(url: "/static_pages/thank_you", method: 'post', local: true) do |form| %>
	<div class="row">
		<div class="col-sm-12 col-md-6 col-lg-4">
			<div class="form-group">
				<%= form.label :name %>
				<%= form.text_field :name, class: "form-control", placeholder: "Enter Name" %>
			</div>        
			<div class="form-group">
				<%= form.label :email, "Email Address" %>
				<%= form.text_field :email, class: "form-control", placeholder: "Enter Email" %>
			</div>
			<div class="form-group">
				<%= form.label :message %>
				<%= form.text_area :message, class: "form-control", placeholder: "Enter Message", rows: "10" %>
			</div>        
		</div><!-- END columns -->
	</div><!-- END row -->
	<%= form.submit "Send", class: 'btn' %>   
<% end %>

<hr>

app/views/static_pages/landing_page.html.erb
<% sleep 2 %>
<h2>Featured Product:</h2>
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  			<!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  			<!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
  	<% @products.each do |product| %>
		  <div class="item<%= " active" if product == @products.first %>">
		    <%= image_tag(product.image_url) %>
		    <div class="carousel-caption">
		     <%= product.name %>
		    </div>
		  </div>
    <% end %>
  </div>

  <div>
    <h2>Hoi</h2>
  </div>

  			<!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>